/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectcostreport;

import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Burcu
 */
public class UI_costreport extends javax.swing.JFrame {

    /**
     * Creates new form UI_costreport
     */
    public UI_costreport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ekle = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        sonuclar = new javax.swing.JTextArea();
        degerlendir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        p_devamlilik = new javax.swing.JComboBox<>();
        p_platform = new javax.swing.JComboBox<>();
        p_gruplari = new javax.swing.JComboBox<>();
        p_suresi = new javax.swing.JComboBox<>();
        sifirla = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ekle.setText("Ekle");
        ekle.setToolTipText("");
        ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekleActionPerformed(evt);
            }
        });

        sonuclar.setEditable(false);
        sonuclar.setColumns(20);
        sonuclar.setRows(5);
        jScrollPane1.setViewportView(sonuclar);

        degerlendir.setText("Değerlendir");
        degerlendir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degerlendirActionPerformed(evt);
            }
        });

        jLabel4.setText("Proje Platformu :");

        jLabel2.setText("Proje Süresi :");

        jLabel3.setText("Proje Devamlılığı :");

        jLabel1.setText("Proje Grupları :");

        p_devamlilik.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Aylık Danışmanlık", "1 Yıllık Danışmanlık", "Sınırsız Danışmanlık", " " }));
        p_devamlilik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_devamlilikActionPerformed(evt);
            }
        });

        p_platform.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Web", "Mobil", "Masaüstü", " " }));

        p_gruplari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Az(1-3)", "Orta(4-7)", "Çok(8-15)", "Daha Çok(15'ten fazla)" }));
        p_gruplari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_gruplariActionPerformed(evt);
            }
        });

        p_suresi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Çok Kısa(0-10 gün)", "Kısa(11-30 gün)", "Orta(31-60 gün)", "Uzun(61-100 gün)", "Çok Uzun(101-150 gün)", " " }));
        p_suresi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_suresiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p_platform, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p_devamlilik, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p_gruplari, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p_suresi, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(p_gruplari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p_suresi, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(p_devamlilik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(p_platform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69))
        );

        sifirla.setText("Sıfırla");
        sifirla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sifirlaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ekle, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sifirla, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(degerlendir, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ekle)
                    .addComponent(sifirla))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(degerlendir)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void p_gruplariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_gruplariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_gruplariActionPerformed

    private void p_suresiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_suresiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_suresiActionPerformed

    private void p_devamlilikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_devamlilikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_devamlilikActionPerformed
 sonuc s = new sonuc();
    HesaplarModel hesapModel;
    List<jsonModel> list=new ArrayList<jsonModel>();
    List<String> sonuclist=new ArrayList<String>();
    private void ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekleActionPerformed
        // ekle
        
        sonuclar.setText(p_gruplari.getSelectedItem() + "\n" +  p_suresi.getSelectedItem() + "\n" +
            p_devamlilik.getSelectedItem()+ "\n"  + p_platform.getSelectedItem());
        list.add(new jsonModel(
                p_gruplari.getSelectedItem().toString(),
                p_suresi.getSelectedItem().toString(),  
                p_devamlilik.getSelectedItem().toString(),
                p_platform.getSelectedItem().toString()));
        
        hesapModel= new HesaplarModel(
            p_gruplari.getSelectedIndex(), 
            p_suresi.getSelectedIndex(),
            p_devamlilik.getSelectedIndex(), 
            p_platform.getSelectedIndex());
    Hesaplar hesaplar= new Hesaplar();
    sonucGonder = "Bu yazılım projenin bedeli yaklaşık " + String.valueOf(hesaplar.Hesaplar(hesapModel)) + " TL'dir."; 
    sonuclist.add(sonucGonder);   
    s.sonucFonk(list,sonuclist);
        
    }//GEN-LAST:event_ekleActionPerformed
    String sonucGonder;
    private void sifirlaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sifirlaActionPerformed
        // TODO add your handling code here:
        sonuclar.setText("");
        p_gruplari.setSelectedIndex(0);
        p_suresi.setSelectedIndex(0);
        p_devamlilik.setSelectedIndex(0);
        p_platform.setSelectedIndex(0);
        
   
    }//GEN-LAST:event_sifirlaActionPerformed
   
    private void degerlendirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degerlendirActionPerformed
        // TODO add your handling code here:
          
        s.setVisible(true);
        
    }//GEN-LAST:event_degerlendirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI_costreport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI_costreport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI_costreport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI_costreport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI_costreport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton degerlendir;
    private javax.swing.JButton ekle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> p_devamlilik;
    private javax.swing.JComboBox<String> p_gruplari;
    private javax.swing.JComboBox<String> p_platform;
    private javax.swing.JComboBox<String> p_suresi;
    private javax.swing.JButton sifirla;
    private javax.swing.JTextArea sonuclar;
    // End of variables declaration//GEN-END:variables
}
